// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlX4B1c4LlSG2YB-K-Nhbyc9zjzEquEGw',
    appId: '1:177339568494:web:353d52fd7fc7189d9cf17f',
    messagingSenderId: '177339568494',
    projectId: 'edugenai-11196',
    authDomain: 'edugenai-11196.firebaseapp.com',
    storageBucket: 'edugenai-11196.firebasestorage.app',
    measurementId: 'G-PGV1MJVZEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKBEdxIOI7-S0_X84Wl01hyTYCZnjvoWY',
    appId: '1:177339568494:android:83e003310222231b9cf17f',
    messagingSenderId: '177339568494',
    projectId: 'edugenai-11196',
    storageBucket: 'edugenai-11196.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8R4Zel8IjH0aB7FF3oxCFIA2VAofgQRU',
    appId: '1:177339568494:ios:096d7da163f49f1b9cf17f',
    messagingSenderId: '177339568494',
    projectId: 'edugenai-11196',
    storageBucket: 'edugenai-11196.firebasestorage.app',
    iosClientId: '177339568494-jv9ddil0gt0jikit8ljnk3r4qcib9k55.apps.googleusercontent.com',
    iosBundleId: 'com.example.edugenai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8R4Zel8IjH0aB7FF3oxCFIA2VAofgQRU',
    appId: '1:177339568494:ios:096d7da163f49f1b9cf17f',
    messagingSenderId: '177339568494',
    projectId: 'edugenai-11196',
    storageBucket: 'edugenai-11196.firebasestorage.app',
    iosClientId: '177339568494-jv9ddil0gt0jikit8ljnk3r4qcib9k55.apps.googleusercontent.com',
    iosBundleId: 'com.example.edugenai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlX4B1c4LlSG2YB-K-Nhbyc9zjzEquEGw',
    appId: '1:177339568494:web:c25bfbed9818db359cf17f',
    messagingSenderId: '177339568494',
    projectId: 'edugenai-11196',
    authDomain: 'edugenai-11196.firebaseapp.com',
    storageBucket: 'edugenai-11196.firebasestorage.app',
    measurementId: 'G-XETBZDXPMR',
  );
}
